kaizen:
  host: "http://localhost:"
api:
  profile:
    context: "/profile"
    port: 8079
  checklist:
    port: 8085
  habit:
    port: 8089
  weight:
    context: "/weight"
    port: 8081
  notepad:
    context: "/notepad"
    port: 8087